"""
Pydantic Schemas for Gemini Multimodal AI Analysis (Phase 5).
"""

from typing import List
from pydantic import BaseModel, Field


class GeminiComplaintDraft(BaseModel):
    """
    Validated structured output generated by Gemini Multimodal API.
    Conforms to CivicFlow Phase 5 specifications.
    """
    category: str = Field(
        ...,
        description="Standard municipal category e.g. Waste, Road Damage, Drainage, Streetlight, Water Leakage, Public Infrastructure, Traffic/Safety, Sanitation, Other."
    )
    observed_issue: str = Field(
        ...,
        description="Objective description of the physical defect directly visible in the image."
    )
    citizen_claim: str = Field(
        ...,
        description="Professional articulation of what the citizen is reporting without inventing facts."
    )
    formal_summary: str = Field(
        ...,
        description="A clear, professional, respectful municipal complaint ready for public works triage."
    )
    urgency_level: str = Field(
        ...,
        description="Assessed triage level: strictly one of 'LOW', 'MEDIUM', 'HIGH', or 'CRITICAL', based strictly on visible hazards."
    )
    warnings: List[str] = Field(
        default_factory=list,
        description="Any noticed inconsistencies, poor lighting warnings, or missing details."
    )
